### PR TITLE
[FIXED] Unable to reuse nested routers

### PR DESCRIPTION
**Pull request by lichaozhy**
shallow clone & inherit Layer.prototype is useful.

### CODE REVIEW

**Comment by lichaozhy** [comment]
Do not use this. It has to be changed

**Comment by lichaozhy** [comment]
https://github.com/ZijianHe/koa-router/issues/244#issuecomment-363776228

For #18 #22

The essential reason is that router need to be deeply cloned. So I offer a low-complexity solution. Just middleware router & its layers need to be cloned. It works now.

**Comment by niftylettuce** [comment]
Can you add tests?

**Comment by lichaozhy** [comment]
OK, how do you like the new commit?

**Comment by lichaozhy** [comment]
On the whole, it is just a compensatory scheme. The key mistake is the design about Router#use() method. It could not be use to handle both normal functions and `Router` instances. Only the "information" of router is important when `use()` by another router instance. So I think the solution cloning a new router is safe and effective.

The other things about `koa-router` are very good I think. But it still needed to refactor for more reliable and robust.

**Comment by Telokis** [comment]
Is there anything left to do on this PR?

**Comment by niftylettuce** [comment]
v8.0.3 is released to npm! 🎉

**Pull request merged**
