### PR TITLE
Test Coverage Improved 

### PR DESCRIPTION
**Pull request by JacobMGEvans**
- The layer has been increased to all 100's coverage
- The router has had an additional logic control flow line covered reducing uncovered lines from 4 to 3
- **Rebase SUCCESS!** 🎉🎊funny enough my Prettier added a CRLF line to a file 
@niftylettuce 
Screen Shot 2020-03-11 at 9 34 24 PM

### CODE REVIEW

**Comment by JacobMGEvans** [comment]
@niftylettuce Since I don't have the option to squash the PR I did it manually and created this new PR 
I'll try to keep the forked branches up to date with the upstream master, doing this a little new to me for stuff like this lol

**Comment by niftylettuce** [comment]
Any chance you could update this one more before I merge it @JacobMGEvans ?

**Comment by JacobMGEvans** [comment]
Hmm, seems to be a lot of changes since this PR. Are most of the tests currently passing in your master branch?

**Comment by JacobMGEvans** [comment]
I think Travis needs to have a Test check for PR's??

**Comment by JacobMGEvans** [comment]
Currently if I pull in remote master and run the tests I get this. Thats resolving the merge conflict with accepting incoming changes ("theirs").
Screen Shot 2020-04-27 at 8 51 56 PM
Screen Shot 2020-04-27 at 8 52 32 PM

**Comment by 3imed-jaberi** [comment]
@JacobMGEvans, thank u for your PR.
 I'm going to work on this.

**Comment by niftylettuce** [comment]
v9.0.1 released https://github.com/koajs/router/releases/tag/v9.0.1

**Pull request closed without merging**
