### PR TITLE
Refactor/for each to forloops

### LINKED ISSUE #42: `forEach` should be rewritten to `for` loop for optimized boot performance

### PR DESCRIPTION
**Pull request by JacobMGEvans**
- forEach on methods converted to ES1 `for` loop - leaving comments for PR review confirmation
  - Once the PR has been reviewed and the logic is confirmed I will remove the commented out `forEach` logic. 
- forEach converted to `for` loop -- function ensures middleware is a function
- let & const to var for potential small perf -- tests passing in both prior commits 

should resolve #42 
Screen Shot 2020-02-01 at 8 42 15 PM

### CODE REVIEW

**Comment by JacobMGEvans** [comment]
Still have more `forEach` to refactor, thought I would get the ball rolling with PR review, suggestions, ect... 😄

**Comment by fedyk** [comment]
@JacobMGEvans thanks for your PR. Would you be able to create some simple benchmark test to prove that those changes improve boot perf?

**Comment by JacobMGEvans** [comment]
> @JacobMGEvans thanks for your PR. Would you be able to create some simple benchmark test to prove that those changes improve boot perf?

I'll definitely give it a shot, any suggestions on tooling or the like? Or should I add actual tests that are focusing on execution time to the test suites?

**Comment by JacobMGEvans** [comment]
The only forEach left are in the testing suites, which converting those seemed unnecessary since they would only affect development environments.

Still unclear on how benchmarking should be done for a clear picture of the potential effects of the refactoring done.

**Comment by JacobMGEvans** [comment]
I fixed the benchmark code... Mostly. I wasn't sure what the nest() method was replaced by in the API so I used .middleware() seemed to handle the change ok. 

I will create a separate PR with the benchmark code changes.  😃

**Comment by fedyk** [comment]
@JacobMGEvans there is popular library [benchmarkjs](https://benchmarkjs.com/) for performance tests. But I'm not sure it is suitable for testing boot time(the metric you are trying to improve by this PR).

You can use nodejs build-in profiler from V8 and try to test your changes. [Here](https://nodejs.org/en/docs/guides/simple-profiling/) guide from Node.js docs. 

In case of profiling the boot time, you can create file `test.js`:
```
const Route = require("./")
```

And then run `NODE_ENV=production node --prof test.js` and `node --prof-process isolate-0x102808000-v8.log  > processed.txt`. Basically, in `processed.txt` you would have a result of profiling. By running it a few times for the master and your branch, you should have the raw result of your changes.

This should be enough for test parsing and compiling times.

**Comment by JacobMGEvans** [comment]
> @JacobMGEvans there is popular library [benchmarkjs](https://benchmarkjs.com/) for performance tests. But I'm not sure it is suitable for testing boot time(the metric you are trying to improve by this PR).
> 
> You can use nodejs build-in profiler from V8 and try to test your changes. [Here](https://nodejs.org/en/docs/guides/simple-profiling/) guide from Node.js docs.
> 
> In case of profiling the boot time, you can create file `test.js`:
> 
> ```
> const Route = require("./")
> ```
> 
> And then run `NODE_ENV=production node --prof test.js` and `node --prof-process isolate-0x102808000-v8.log > processed.txt`. Basically, in `processed.txt` you would have a result of profiling. By running it a few times for the master and your branch, you should have the raw result of your changes.
> 
> This should be enough for test parsing and compiling times.

I'll definitely give it a try 😁

**Comment by JacobMGEvans** [comment]
**Boot Profiling Files:**
[RefactoredProcessed.txt](https://github.com/koajs/router/files/4162801/RefactoredProcessed.txt)
[MasterProcessed.txt](https://github.com/koajs/router/files/4162802/MasterProcessed.txt)

_I noticed some reduced ticks in the RefactoredProcessed and even some processes completely gone, though I might just be missing them._

**Comment by niftylettuce** [comment]
No need for benchmarks

**Comment by niftylettuce** [comment]
v8.0.7 released https://github.com/koajs/router/releases/tag/v8.0.7

**Pull request merged**
