### PR TITLE
Benchmark code fixed -- Port & nest() were not working

### PR DESCRIPTION
**Pull request by JacobMGEvans**
- `wrk` needs to be installed locally or alternatively it can be installed into dev dependencies. 
- .next() seems to longer be part of the API, I used .middleware() not sure of tests similar but it worked as a stopgap for completing the tests.
- Port in the shell file didn't seem to be passing its variable into Node process environment, which server.js was using to listen on, hardcoding the port in both files solved the issue. 

related to #52

### CODE REVIEW

**Comment by niftylettuce** [comment]
Did you want to put `wrk` in dev deps and then this would be ok to merge?

**Comment by JacobMGEvans** [comment]
I was up in the air, I had to brew install wrk for this to operate properly. Weirdly .nest() was giving me an issue though I saw that you had fixed it.

**Comment by JacobMGEvans** [comment]
I added the `wrk` to dev dependencies and will work on having the scripts utilize that later. 

Eventually, I want to improve the perfing tooling/code and make it more usable maybe even integrate something like a perf/health check into Travis or something.

**Comment by niftylettuce** [comment]
lmk if this is ready?

**Comment by JacobMGEvans** [comment]
Ready.

**Comment by niftylettuce** [comment]
@JacobMGEvans 	Could we use `get-port` as an alternative to hardcoded `3333`? https://github.com/sindresorhus/get-port

**Comment by JacobMGEvans** [comment]
> @JacobMGEvans Could we use get-port as an alternative to hardcoded 3333? https://github.com/sindresorhus/get-port

@niftylettuce 
Could potentially use .env https://github.com/motdotla/dotenv

which would also allow for more environment variables to be dynamic and with hardcoded fallbacks.

**Pull request merged**
