### PR TITLE
Add test for optional route parameter

### PR DESCRIPTION
**Pull request by smarts**
Test for #40

### CODE REVIEW

**Comment by smarts** [comment]
Sure. Both styles were in the code already, so @3imed-jaberi how would you feel about me doing a sweep and fixing it everywhere in this file?
On an unrelated note as a bit of constructive criticism: in the future, a simple `.` or `?` is probably better. Using `!!` comes across a bit aggressive and could alienate contributors.

**Comment by niftylettuce** [comment]
@smarts no worries - they didn't mean to alienate in any way, @3imed-jaberi is excited and happy to see your contributions! 🎉 🎉

**Comment by smarts** [comment]
Interesting, this test passes now. Looks like the bug has been fixed.

**Comment by niftylettuce** [comment]
thanks @smarts

**Comment by smarts** [comment]
Happy to help. Thanks to you @niftylettuce and @3imed-jaberi as well!

**Comment by 3imed-jaberi** [comment]
@smarts,  sorry ... I didn't mean to insult or belittle or anything negative ... I just tried to provide a comment summarizing the situation in this PR and I wanted to say thank you for your contribution and that your work provides a good example ..

**Pull request merged**
