### PR TITLE
Fix additional entry inejcted to params

### LINKED ISSUE #113: Router with prefix and middleware causes additional entry to get injected into ctx.params
node.js version: 12.20.1

npm/yarn and version: npm 6.14.10

`@koa/router` version: 10.0.0

`koa` version: 2.13.1

#### Code sample:

```js
const Koa = require('koa');
const Router = require('@koa/router');

async function middleware(ctx, next) {
  await next();
}

const router = new Router({ prefix: '/:ping/pong' });
router.use(middleware);

router.get('/', ctx => {
  ctx.body = ctx.params;
});

const app = new Koa();
app.use(router.routes())
app.use(router.allowedMethods());
app.listen(3000);
```

#### Expected Behavior:

GET `http://localhost:3000/ping/pong`

```json
{"ping":"ping"}
```

#### Actual Behavior:

GET `http://localhost:3000/ping/pong`

```json
{"0":"","ping":"ping"}
```

#### Additional steps, HTTP request details, or  to reproduce the behavior or a test case:

- The prefix must be a named parameter (in this case, `/:ping`) followed by a static one (here, `/pong`)
- The `router.use(middleware)` must be called without the optional `path` parameter, using `router.use('/', middleware)` works fine

### PR DESCRIPTION
**Pull request by 3imed-jaberi**
fix #113

### CODE REVIEW

**Comment by dominicegginton** [comment]
Can you write a unit test for this? 🧪

**Review by 3imed-jaberi — COMMENTED** [review]
done and ready to merge

**Comment by niftylettuce** [comment]
@3imed-jaberi minor version bump correct?

**Comment by 3imed-jaberi** [comment]
> @3imed-jaberi minor version bump correct?

@niftylettuce, yes

**Comment by niftylettuce** [comment]
v10.1.0 released to npm 🎉  thank you @3imed-jaberi 🙇 

https://github.com/koajs/router/releases/tag/v10.1.0

**Pull request merged**
