### PR TITLE
refactor(dependencies): remove urijs dependency

### PR DESCRIPTION
**Pull request by panva**
Removes the (imho unnecessary) dependency on userland `urijs` module. I wanted to use the WHATWG `URL` API but alas that one does not support relative URLs.

### CODE REVIEW

**Comment by panva** [comment]
I am aware that the used methods are marked as deprecated but its worth noting its a [documentation only deprecation](https://nodejs.org/api/deprecations.html#deprecations_dep0116_legacy_url_api) and that the functions are imho unlikely to be removed unless an alternative solution in core stdlib has that functionality, see [here](https://github.com/nodejs/node/issues/25099), and [here](https://github.com/nodejs/node/issues/23694).

**Comment by panva** [comment]
> LGTM 👍 !
> But, I have a suggestion ..
> 
> ```
>     replaced = parseUrl(replaced)
>     if (typeof options.query === 'string') {
>       replaced.search = options.query;
>     } else {
>       replaced.search = undefined
>       replaced.query = options.query
>     }
>     
>     return formatUrl(replaced)
> ```

resolved, dunno what i was thinking ...

**Comment by niftylettuce** [comment]
I fixed the conflict in the wrong way, fixing, one moment.

**Comment by niftylettuce** [comment]
Fixed 6131069

**Pull request merged**
